name: Deploy to ACI

on:
  push:
    branches:
      - github-workflow

env:
  ACR_NAME: lmsnewregistry
  ACR_LOGIN_SERVER: 'lmsnewregistry.azurecr.io'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker images and Deploy to ACI
        run: |
          npm install -g npm@9.6.6
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az acr login --name lmsregistry
          az acr build --image lms-public-api:{{.Run.ID}} --registry lmsregistry ./api/
          az webapp config container set --name lms-web-v2 --resource-group lmsnew  --docker-custom-image-name lmsregistry.azurecr.io/lms-public-api:{{.Run.ID}}
          az acr build --image lms-web:{{.Run.ID}} --registry lmsregistry ./webapp/
          az webapp config container set --name lmsnew --resource-group lmsnew  --docker-custom-image-name lmsregistry.azurecr.io/lms-web:{{.Run.ID}}
