name: Deploy to ACI

on:
  push:
    branches:
      - main

env:
  ACR_NAME: lmsnewregistry
  ACR_LOGIN_SERVER: 'lmsnewregistry.azurecr.io'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/2.9.0/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin/

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set ACR login server
        id: acr_login
        run: echo "ACR_LOGIN_SERVER=$(az acr show --name ${{ env.ACR_NAME }} --query 'loginServer' -o tsv)" >> $GITHUB_ENV

      - name: Log in to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push Docker images
        run: |
          export DOCKER_BUILDKIT=1
          export COMPOSE_DOCKER_CLI_BUILD=1
          docker-compose build
          docker-compose push

      - name: Deploy to ACI
        run: |
          az container create \
            --resource-group lmsnew \
            --name lms-container \
            --image ${{ env.ACR_LOGIN_SERVER }}/lms-image \
            --registry-login-server ${{ env.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
            --dns-name-label lms-new \
            --ports 80 \
            --command-line "docker-compose -f docker-compose.yml up"
          az container show \
            --resource-group lmsnew \
            --name lms-container \
            --query 'ipAddress.ip' \
            --output tsv
