name: Deploy to ACI

on:
  push:
    branches:
      - github-workflow

env:
  ACR_NAME: lmsnewregistry
  ACR_LOGIN_SERVER: 'lmsnewregistry.azurecr.io'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin/

      - name: Build and push Docker images and Deploy to ACI
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          npm cache clean --force
          npm install -g npm@9.6.6
          docker-compose build
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az container create \
            --resource-group lmsnew \
            --name lms-container \
            --registry-login-server ${{ env.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
            --dns-name-label lms-new \
            --ports 80 \
            --restart-policy Always \
            --command-line "docker-compose up" \
            --file docker-compose.yml \
            --environment-variables \
              WEBSITES_ENABLE_APP_SERVICE_STORAGE=false \
              WEBSITE_RUN_FROM_PACKAGE=https://github.com/Aravi4143/lms-public/archive/refs/heads/main.zip
          az container show \
            --resource-group lmsnew \
            --name lms-container \
            --query 'ipAddress.ip' \
            --output tsv
